### ISSUE TITLE
Feature Request - Add troubleshooting info

### ISSUE THREAD

**Issue by rperciaccante** [tango2590/Hughes-Power-Watchdog#2]
Add device attributes that help with connectivity troubleshooting:

`textsensor:
    # Include ESPHome version in device attributes
  - platform:                     version                   
    name:                         Watchdog Monitor ESPHome Version
    id:                           watchdog_monitor_esphome_version

  - platform:                     wifi_info
    ip_address:
      name:                       Watchdog Monitor IP Address
      id:                         watchdog_monitor_host_ip
      icon:                       mdi:fingerprint
    ssid:
      name:                       Watchdog Monitor Connected SSID
      id:                         watchdog_monitor_host_ssid
      icon:                       "mdi:router-wireless"
      
  - platform:                     template                   
    id:                           watchdog_monitor_host_mac
    name:                         Watchdog Monitor MAC Address
    lambda:                       'return {WiFi.macAddress().c_str()};'
    icon:                         mdi:fingerprint
    update_interval:              1d`

**Comment by tango2590** [comment]
This has been added.
